server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/apus
    username: apus
    password: apus
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:bitnami}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  cetus:
    url: ${CETUS_URL:https://apus-external.herokuapp.com/api/cetus/shipping}
    zip: ${CETUS_ZIP:11111111}
  lyra:
    url: ${LYRA_URL:https://apus-external.herokuapp.com/api/lyra/payment}
    company: ${LYRA_COMPANY:2222}
